data:
  maxlen: 256
  start_idx: 0
  end_idx: 10000
model:
  name: 'LSTM'
  max_words: 10000
  emb_size: 128
  hid_size: 128
  drop_out: 0.5
  num_layers: 3
  max_norm: 1
  bidirectional: True
optimizer: 'Adam'
scheduler: 
  name: 'ReduceLROnPlateau'
  step_size: 7
  gamma: 0.1
  patience: 2
lr: 2.0e-03
weight_decay: 1.0e-06
batchsize: 256
epoch: 40
num_worker: 8